# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GovHackApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GovHackApp
  pod 'MobileCenter', '~> 0.10.1'
  pod 'RNMobileCenterShared', '~> 0.7.0'

  

  target 'GovHackAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'GovHackApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GovHackApp-tvOS

  target 'GovHackApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
